- scripts/setup_new_sdk.sh
Correct API docs location in setup script
> fix: update API docs location

- scripts/setup_new_sdk.sh
If the default branch is master, you will need to allow updating head
when doing git fetch. Otherwise, git fetch will fail with
ambiguous argument 'origin/master'.
> fix: allow update head when checking out openfga/sdk-generator

- config/clients/go/template/credentials.mustache
- config/clients/go/template/fga_test.mustache
Fix validation of config in go-sdk. Validation func is applying client_credentials validation to api_token cred method.
> fix(go-sdk): validate correct credentials method config

- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/modelEnum.mustache
- config/clients/dotnet/template/modelInnerEnum.mustache
- config/clients/dotnet/template/modelJsonStringEnumMemberConverter.mustache
- config/clients/dotnet/template/models_test.mustache
Change TupleOperation to TUPLE_OPERATION_WRITE and TUPLE_OPERATION_DELETE Close 
- Close https://github.com/openfga/sdk-generator/issues/7
> fix: dotnet unable to deserialize ReadChangesResponse

- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/fga_test.mustache
Update UT and generated README to reflect the fact that TypeDefinitions is no longer defined
- Close https://github.com/openfga/sdk-generator/issues/30
> chore: update README and unit test for dotnet and Go

- Makefile
- config/clients/js/template/tests/index.test.ts.mustache
1.  Fix Makefile so that unit test failure will be identified as CICD failure
2. Remove TypeDefinitions from JS unit test
Close https://github.com/openfga/sdk-generator/issues/32
> fix: correct CICD tool + remove TypeDefinitions ref

- config/clients/python/template/api_client.mustache
- config/clients/python/template/exceptions.mustache
Python SDK to remove header info from error
> fix: python SDK to remove header info from error

- config/clients/python/template/__init__package.mustache
- config/clients/python/template/api.mustache
- config/clients/python/template/api_client.mustache
- config/clients/python/template/api_test.mustache
- config/clients/python/template/configuration.mustache
- config/clients/python/template/credentials.mustache
- config/clients/python/template/exceptions.mustache
Update python SDK to use error name similar to other SDKs
N/A
> fix: update python SDK error to use standardize error name

- config/clients/python/template/api_test.mustache
- config/clients/python/template/exceptions.mustache
Python SDK exception should contain selected header info
Close https://github.com/openfga/sdk-generator/issues/38
> feat: Python SDK exception should contain specific FGA header info

- config/clients/dotnet/template/api_test.mustache
- config/clients/dotnet/template/modelGeneric.mustache
.NET sdk not able to handle null response for non-required content. 
Close https://github.com/openfga/dotnet-sdk/issues/5
> fix: dotnet sdk not handling null DeletedAt for ListStores

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
chore of bumping .NET version and update release notes
> chore(dotnet-sdk): bump version and update release note

- Makefile
- config/clients/go/template/go.mod.mustache
- config/clients/go/template/go.sum
Also use a more recent GoLang Docker image to ensure latest packages are used.
> chore(go-sdk): bump dependency packages (x/net)

- config/clients/python/template/requirements.mustache
Updating setup tools package due to sec. vulnerability identified.
Close https://github.com/openfga/sdk-generator/issues/60
> chore: update setup tools in python SDK

- config/clients/dotnet/template/Client_ApiClient.mustache
- config/clients/dotnet/template/api_test.mustache
Authorization header was not being sent along when `ApiToken` credential method was used. The reason is that we were instantiating the client before updating the default headers.
Thanks to @Mattieeec3 for raising the issue and identifying the fix.
- fixes https://github.com/openfga/sdk-generator/issues/58
> fix(dotnet-sdk): resolve authorization token not send when ApiToken used

- scripts/setup_new_sdk.sh
> fix(generator): sdk setup script created the wrong file and missed the sdk id

- config/clients/python/config.overrides.json
- config/clients/python/template/README_api_endpoints.mustache
- config/clients/python/template/README_models.mustache
Use absolute links for Python SDK readme so that pypi users can access the README links and point to the github page.
Close https://github.com/openfga/sdk-generator/issues/84
> fix: correct links in pypi readme

- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/api_test.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/js/template/tests/helpers/nocks.ts.mustache
- config/clients/js/template/tests/index.test.ts.mustache
- config/clients/python/template/README_calling_api.mustache
- config/clients/python/template/api_test.mustache
- https://github.com/openfga/api/pull/71
- dotnet is done in https://github.com/openfga/sdk-generator/pull/104
> chore: fix go, js and py sdks to account for schema_version being required

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/Client/Client.mustache
- config/clients/dotnet/template/Client/Model/ClientCheckRequest.mustache
- config/clients/dotnet/template/Client/Model/ClientListObjectsRequest.mustache
- config/clients/dotnet/template/Client/Model/ClientListRelationsRequest.mustache
- config/clients/dotnet/template/Client/Model/ClientTupleKey.mustache
- config/clients/dotnet/template/Client/Model/ClientWriteAssertionsRequest.mustache
- config/clients/dotnet/template/Client/Model/ClientWriteAuthorizationModelRequest.mustache
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/README_calling_api.mustache
- fix: changed interface of contextual tuples in `ClientListObjects` to be `ClientTupleKey` instead of `TupleKey`
- fix: Client `WriteAuthorizationModel` now expects `ClientWriteAuthorizationModelRequest` instead of `WriteAuthorizationModelRequest`
- chore: changed a few interfaces to expect interfaces instead of classes
- fixes: https://github.com/openfga/dotnet-sdk/issues/17
> fix(dotnet-sdk): v0.2.3 with a fix to the interface of ClientListObjects

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/Client_OAuth2Client.mustache
- config/clients/dotnet/template/api_test.mustache
- Related: https://github.com/openfga/dotnet-sdk/issues/19
- Generates: https://github.com/openfga/dotnet-sdk/pull/20
> fix(dotnet-sdk): interpret client credentials token expiry period as seconds

- config/clients/python/template/README_calling_api.mustache
Use list_stores method instead of get_store method in Python README example.
Fix a little typo in the Python list stores example from README.
> chore(python-sdk): fix readme list stores example

- config/clients/go/config.overrides.json
- config/clients/go/template/api.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/client/errors.mustache
- config/clients/go/template/configuration.mustache
- config/clients/go/template/utils/utils.mustache
- config/clients/go/template/utils/utils_test.mustache
Go SDK should validate auth model id and store id to ensure they are valid ulid 
Part of https://github.com/openfga/go-sdk/issues/19
Generated Go Code: https://github.com/openfga/go-sdk/pull/28
> fix(go-sdk): ulid for auth model id and store id to be validated

- Makefile
- config/clients/dotnet/template/Configuration_Configuration.mustache
- config/clients/go/template/configuration.mustache
- config/clients/js/template/configuration.mustache
- config/clients/python/template/api_client.mustache
- config/common/config.base.json
- scripts/build_client.sh
Prevent string manipulation for user agent by rendering appropriate value during builds.
> fix: use static user agent value

- scripts/build_client.sh
follow up to #136 to prevent deleting .git directory and other files when clearing out output directories.
https://github.com/openfga/sdk-generator/pull/136
> fix: exclude files when clearing output dirs

- config/clients/python/template/README_calling_api.mustache
Correct python-SDK readme issues
Implement changes for https://github.com/openfga/python-sdk/pull/32 and https://github.com/openfga/python-sdk/pull/31
Corresponding Python SDK changes: https://github.com/openfga/python-sdk/pull/33
> fix(python-sdk): correct README

- config/clients/go/template/client/client.mustache
OpenFgaClient did not satisfy SdkClient interface as there are discrepancy in ReadAuthorizationModel and ReadLatestAuthorizationModel method
Close https://github.com/openfga/go-sdk/issues/34
Corresponding go-sdk changes https://github.com/openfga/go-sdk/pull/35
> fix(go-sdk): OpenFgaClient should satisfy SdkClient interface

- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
chore of bumping js-sdk dependencies (audit fix)
Corresponding js-sdk changes: https://github.com/openfga/js-sdk/pull/22
> chore(js-sdk): bump dependencies

- config/clients/go/template/api.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
For Go-SDK, allow empty string for ulid
Close https://github.com/openfga/go-sdk/issues/36
Corresponding Go-SDK change: https://github.com/openfga/go-sdk/pull/37
> fix(go-sdk): allow empty string for ulid

- config/clients/go/template/client/client.mustache
For Go-SDK, there is a path where we do not allow empty ulid
Follow up on https://github.com/openfga/sdk-generator/pull/145
> fix(go-sdk): miss path where we validate ulid

- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
Client not taking in details for option and body in list stores/read changes etc. In addition, read auth model does not check and error when auth model is id string is empty
Close https://github.com/openfga/go-sdk/issues/41
Close https://github.com/openfga/go-sdk/issues/42
Corresponding Go SDK changes: https://github.com/openfga/go-sdk/pull/43
> fix(go-sdk): client option + body not respected

- config/clients/dotnet/patches/add-missing-first-param.patch
- config/clients/js/patches/add-missing-first-param.patch
Since api swagger document is updated, we need to update API.ts patch to reflect the new description.
> chore(js-sdk): update JS patch

- Makefile
- config/clients/python/template/test-requirements.mustache
Temporarily pins pycodestyle, a dependency for autopep8, to 2.10.0 until a fix upstream is released.
Fixes #162.
> fix: temporarily pin pycodestyle to 2.10.0

- config/clients/python/template/api_test.mustache
- config/clients/python/template/client/models/list_objects_request.mustache
- config/clients/python/template/client/models/list_relations_request.mustache
- config/clients/python/template/client/models/tuple.mustache
- config/clients/python/template/client/models/write_single_response.mustache
Originally done to fix CI (see #161) but unnecessary for CI since #163 
Now it's just a misc cleanup PR. Most of the Python code/templates use spaces, only a handful of places had tabs
> fix(python): Convert tabs to spaces

- config/clients/java/template/libraries/native/JSON.mustache
Currently when building the Java SDK there is a warning that pops up due to using the deprecated `ObjectMapper.configure(..., ...)` methods.
```
> Task :compileJava
Note: /module/src/main/java/dev/openfga/api/invoker/JSON.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
https://github.com/FasterXML/jackson-databind/blob/2.16/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L2507-L2517
> fix(java): Update to use JsonMapper

- config/clients/go/template/configuration.mustache
Allow setting `Debug` to true when configuring a new client.
> feat(go): thread debug client configuration

- config/clients/go/template/client/client.mustache
Guard against calling `ReadAuthorizationModel` with an empty string.
https://github.com/openfga/cli/pull/125
> fix(go): guard against empty model id

- config/clients/java/config.overrides.json
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
Updates the location of classes like ApiClient and Configuration to be `dev.openfga.api.client` instead of `dev.openfga.api.invoker`. This matches conventions in other OpenFGA projects
Generates these changes: https://github.com/openfga/java-sdk/pull/4
> misc(java): Rename package path of client components

- config/clients/java/config.overrides.json
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
Switches to async style Java.
The core of async is in HttpClient, and the ability to configure things like thread pools is in [HttpClient.Builder.executor(Executor)](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Builder.html#executor%28java.util.concurrent.Executor%29)
> refactor(java): Async

- config/clients/js/template/client.mustache
- config/clients/js/template/tests/client.test.ts.mustache
NOTE: BatchCheck does not have the raw response yet
- SDK PR: https://github.com/openfga/js-sdk/pull/31
> fix(js-sdk): raw response in client check

- config/clients/js/template/client.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- Addresses the JS part of #183 
- SDK PR: https://github.com/openfga/js-sdk/pull/32
> fix(js-sdk): list relations should throw when an underlying check errors

- config/clients/java/config.overrides.json
- config/clients/java/template/config-BaseConfiguration.java.mustache
- config/clients/java/template/config-Configuration.java.mustache
- config/clients/java/template/config-ConfigurationOverride.java.mustache
- config/clients/java/template/config-ConfigurationTest.java.mustache
- config/clients/java/template/libraries/native/api.mustache
Allows Configuration to be overridden per request.
Rendered version can be found here: https://github.com/openfga/java-sdk/pull/7
Close #175
> feat(java): Configuration overrides

- Makefile
Pin autopep8 used while running `make build-client-python` to avoid breaking issue in 2.0.3 release.
https://github.com/hhatto/autopep8/issues/702
> chore: pin autopep8 to 2.0.2

- config/clients/python/template/client/client.mustache
- config/clients/python/template/client/test_client.mustache
- Generates: https://github.com/openfga/python-sdk/pull/36
- Issue: https://github.com/openfga/python-sdk/issues/35
> fix(python-sdk): fix crash in ClientCheck w/ ctx tuples

- config/clients/go/template/model_simple.mustache
There was a small logic on handlebars causing to create if true statements on the golang sdk as we can see [here](https://github.com/openfga/go-sdk/blob/main/model_authorization_model.go#L137)
with this new implementation the code is now like this:
*before*
```go
func (o ListObjectsRequest) MarshalJSON() ([]byte, error) {
toSerialize := map[string]interface{}{}
if o.AuthorizationModelId != nil {
toSerialize["authorization_model_id"] = o.AuthorizationModelId
}
if true {
toSerialize["type"] = o.Type
}
if true {
toSerialize["relation"] = o.Relation
}
if true {
toSerialize["user"] = o.User
}
if o.ContextualTuples != nil {
toSerialize["contextual_tuples"] = o.ContextualTuples
}
return json.Marshal(toSerialize)
}
```
*after*
```go
func (o ListObjectsRequest) MarshalJSON() ([]byte, error) { …
```
> Adjust logic on handlebars to avoid 'if true' statement on models

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/README_initializing.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientIntegrationTest.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/config-ClientListStoresOptions.java.mustache
- config/clients/java/template/config-ClientReadAuthorizationModelOptions.java.mustache
- config/clients/java/template/config-ClientReadAuthorizationModelsOptions.java.mustache
- config/clients/java/template/config-ClientReadChangesOptions.java.mustache
- config/clients/java/template/config-ClientWriteAssertionsOptions.java.mustache
- config/clients/java/template/libraries/native/api.mustache
- refactor(java-sdk): simplify OpenFgaClient and OpenFgaApi constructors
- refactor(java-sdk): Add more Options classes, make options class naming consistent
- chore(java-sdk): bump version to 0.1.0
Generates https://github.com/openfga/java-sdk/pull/24
> refactor: simplify constructors, make client options consistent, bump to 0.1.0

- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/client-OpenFgaClientIntegrationTest.java.mustache
ci: adds error logging for tests
fix: makes an expand integration test tolerate whitespace
Generates: https://github.com/openfga/java-sdk/pull/29
> fix(java-sdk): fix integration test failure for write_and_expand

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/client-ClientExpandRequest.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- fix(client): don't send tuple key on empty read request
- fix(client): remove unnecessary parameter from ClientExpandRequest
- chore: bump version to 0.3.0
generates https://github.com/openfga/java-sdk/pull/31
closes https://github.com/openfga/java-sdk/issues/30
> fix(java-sdk): don't send tuple key on empty read request

- config/clients/python/template/client/client.mustache
- config/clients/python/template/client/client_sync.mustache
* feat(python-sdk): run sync batch_check with ThreadPoolExecutor for parallelism
* feat(python-sdk): use asyncio semaphore for streaming batch check
Generates https://github.com/openfga/python-sdk/pull/41
> feat(python-sdk): batch_check updates

- config/clients/dotnet/template/Client/Client.mustache
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/dotnet/template/modelGeneric.mustache
Do not serialize default value.  As such, if read request is provided without any body, it will not serialize tuple_key field.
Close https://github.com/openfga/dotnet-sdk/issues/31
> fix(dotnet): allow case with empty read body

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/client-ClientBatchCheckResponse.java.mustache
- config/clients/java/template/client-ClientCheckRequest.java.mustache
- config/clients/java/template/client-ClientListRelationsResponse.java.mustache
- config/clients/java/template/client-ClientTupleKey.java.mustache
- config/clients/java/template/client-ClientWriteRequest.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/config-ClientBatchCheckOptions.java.mustache
- config/clients/java/template/config-ClientListRelationsOptions.java.mustache
- config/clients/java/template/config-ClientWriteOptions.java.mustache
- config/clients/java/template/errors-FgaInvalidParameterException.java.mustache
* feat(java-sdk): implement listRelations, batchCheck, and non-transaction write
Generates https://github.com/openfga/java-sdk/pull/32
> feat(java-sdk): implement batchCheck, listRelations, and non-transaction write

- config/clients/python/template/README_initializing.mustache
Correct path for sync client import for python SDK
Implement changes for https://github.com/openfga/python-sdk/pull/44
> fix(python): correct path for sync client in README

- config/clients/java/template/.github/workflows/main.yml.mustache
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/client-ClientAssertion.java.mustache
- config/clients/java/template/client-OpenFgaClientIntegrationTest.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- chore(deps): bump the dependencies group with 4 updates (Backport of https://github.com/openfga/java-sdk/pull/34)
- chore(deps): bump the dependencies group with 8 updates (Backport of https://github.com/openfga/java-sdk/pull/35)
- chore(java-sdk): update for latest model changes
Generates https://github.com/openfga/java-sdk/pull/36
> chore(java-sdk): update for interfaces and dependency bumps

- .gitignore
- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
Configurable client_credentials token endpoint for the Java SDK.
Add a `tokenEndpoint` property to the `ClientCredentials` class. The `OAuth2Client` use this property value if not null/blank to query the token. If the property is not set, the previous behavior is applied (default to `<issuer>/oauth/token`).
#238
> feat(java-sdk): configurable token endpoint

- config/clients/go/template/README_initializing.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/credentials.mustache
Add OAuth2 client credentials support to go SDK.
Add an optional scope parameter and make the audience parameter optional. 
#255
> feat(go-sdk): oauth2 client credentials support

- config/clients/java/template/README_initializing.mustache
- config/clients/java/template/config-ClientCredentials.java.mustache
- config/clients/java/template/config-ClientCredentialsTest.java.mustache
- config/clients/java/template/creds-CredentialsFlowRequest.java.mustache
- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
Add OAuth2 client credentials support to java SDK.
Add an optional scope parameter and make the audience parameter optional.
#255
> feat(java-sdk): oauth2 client credentials support

- config/clients/python/template/client/client.mustache
- config/clients/python/template/configuration.mustache
- Fix import order in `python/template/client/client.mustache`
- Fix import order in `python/template/configuration.mustache`
Related to #126
> style(python-sdk): fix import order in client and configuration file templates

- config/clients/python/template/README_calling_api.mustache
- Fix incorrect double slash comment in `python/template/README_calling_api.mustache`
Related to #126
> fix(python-sdk): fix incorrect double slash comments in python-sdk

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/go/CHANGELOG.md.mustache
- config/clients/java/CHANGELOG.md.mustache
- config/clients/js/CHANGELOG.md.mustache
- config/clients/python/CHANGELOG.md.mustache
- JS audit failure resolved in #272
> chore(docs): correctly attribute the python changelog to python

- config/clients/go/template/api_test.mustache
- config/clients/go/template/credentials.mustache
Make token endpoint configurable. I implemented the same way I did [for the java-sdk](https://github.com/openfga/sdk-generator/pull/240).
#238
> feat(go-sdk): configurable client credentials token url

- config/clients/java/config.overrides.json
- config/clients/java/template/creds-AccessToken.java.mustache
- config/clients/java/template/creds-AccessTokenTest.java.mustache
Fixes bug in `AccessToken#isValid()` that caused it to return false when the token is valid, resulting in extraneous calls to fetch new tokens.
Fixes the logic used to check if the token is valid based on its expiry.
https://github.com/openfga/java-sdk/issues/48
> fix(java-sdk): fix token validity check for expiry

- config/clients/java/template/.github/workflows/main.yml.mustache
Port dependabot `gradle-build-action` version bump back to generator.
https://github.com/openfga/java-sdk/pull/42/
> chore(deps): update gradle-build-action

- config/clients/go/template/model.mustache
- config/clients/go/template/model_simple.mustache
The behaviour of json.Marshal is to escape any HTML characters in a string, by using json.Encoder we are able to disable the escaping of these characters
openfga/cli/issues/188
> fix(go-sdk): dont escape HTML characters in conditions

- scripts/build_client.sh
On a clean run, the script wouldn't find any files to remove which meant the `cd -` would never run and put the script back into the top level directory. So, use `||` to ensure that we always run that and end up back in the context of the top level directory.
Closes #73
> fix(build): allow clearing of unwanted files to fail

- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/creds-CredentialsFlowRequest.java.mustache
- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
- config/clients/java/template/libraries/native/ApiClient.mustache
As noted in https://github.com/openfga/java-sdk/issues/47, the OAuth2 credentials should be sent as a url-encoded form post. #281 fixed the content-type, but the request body was still being sent as JSON, which caused the request to fail. This change updates the request to be sent as a `application/x-www-form-urlencode` form post.
* https://github.com/openfga/java-sdk/issues/47
* #281 
* [Draft PR of generated changes](https://github.com/openfga/java-sdk/pull/51)
> fix(java-sdk): send the credentials flow request as form-urlencoded

- config/clients/java/config.overrides.json
- config/clients/java/template/client-ApiClientTest.java.mustache
- config/clients/java/template/libraries/native/ApiClient.mustache
Fixes issue of creating a new `HttpClient` on every request.
As noted in https://github.com/openfga/java-sdk/issues/46, we are currently creating a new `HttpClient` on every request. This change fixes that by building the client when the `ApiClient` is instantiated, and if the `HttpClient.Builder` is updated.
Note that this change does **not** address the retry case, in which we create a new `HttpClient` with a delayed executor. We should still be able to only create one of those, but as its tied to the `Configuration`, which is mutable, need to think a bit more about that scenario.
* https://github.com/openfga/java-sdk/issues/46
> fix(java-sdk): don't create a new HttpClient on every request

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
Release v0.3.2 of Java SDK
- fix: fix token validity check for expiry
- fix: send OAuth2 credentials request as form-urlencoded post
- fix: do not create new http client on every request
> release(java-sdk): v0.3.2

- config/clients/java/template/gitignore.mustache
Updates the `.gitignore` for the java SDK to handle IntelliJ files. Change was originally made to the SDK in [this PR](https://github.com/openfga/java-sdk/pull/51/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947).
> chore(java-sdk): Update .gitignore for IntelliJ

- config/clients/java/template/.github/workflows/main.yml.mustache
Use Java 21 (LTS) instead of Java 20 in CI matrix configuration.
* [Java 21 released in September 2023](https://en.wikipedia.org/wiki/Java_version_history#Java_21)
> chore(java-sdk): use java 21 in CI matrix

- config/clients/python/template/.github/workflows/main.yaml
This PR updates the Python SDK's GitHub publishing workflow to enable [trusted publishing](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) with the Python Package Index.
- Generated change for SDK repository: https://github.com/openfga/python-sdk/pull/64
> chore(python-sdk): enable PyPI trusted publishing

- config/clients/dotnet/template/example/Makefile
- config/clients/go/template/example/Makefile
Noticed that a couple of our SDK examples don't have the docker command configured to start the OpenFGA server; this PR fixes that for repositories where this was missing (dotnet and go)
> fix(go-sdk, dotnet): fix example makefile to run openfga

- config/clients/js/template/client.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/js/template/tests/helpers/nocks.ts.mustache
We currently require passing an object with `type` as an empty string when calling the `OpenFgaClient.readChanges`, this is because we do not mark the `body` param as optional, when in reality it is as it is not required to pass a `type` to the api, and based on our other SDKs this seems a perfectly valid usage.
This is only really obvious when using TypeScript as it will flag the issue, developers who aren't using TypeScript won't see anything wrong until their code runs and the SDK errors when trying to access `body.type`.
```js
const response = await fgaClient.readChanges(); // Expected 1-2 arguments, but got 0. An argument for 'body' was not provided.
```
This PR proposes moving the `body` parameter to be optional, meaning that the above is now valid from a typechecking perspective …
> fix(js-sdk): make body in readChanges optional

- config/clients/js/config.overrides.json
- config/clients/js/template/example/Makefile
- config/clients/js/template/example/README.md.mustache
- config/clients/js/template/example/example1/example1.mjs
- config/clients/js/template/example/example1/package.json.mustache
Adds an example for the JS SDK that copies the structure of the other SDKs of doing:
* Log action about to be performed
* Log outcome/return value
* OR
* Log error and exit
I made the following choices here:
* Usage of ESM instead of CommonJS - Personal opinion that we should be moving to this in documentation
* Usage of top level await/mjs - Avoids having to use an async iiife to allow using async/await
* I _think_ we could move to a `.js` file with a `type` field in the `package.json` of the example if desired
* No `package-lock` committed - It's just another file to maintain and keep in sync between the SDK repo and the generator repo, and realistically adds 0 benefit
These two choices are what primarily drove the require for the `>=16.13.0` (earliest 16 LTS) value in the examples …
> feat(js-sdk): add example js project

- config/clients/dotnet/template/.github/workflows/main.yaml.mustache
- config/clients/dotnet/template/netcore_testproject.mustache
- config/clients/js/template/example/example1/example1.mjs
- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
56673b48706100a335548bf906595557e9fd0a27 - Removes the usage of `Credentials` from the example as there is an issue with providing this, I'll file a separate issue on the SDK repo to fix that.
feb1142481da31a26285807b40d2f001c373a45f - Syncs dep updates from the JS repo
b0b3b2c589d4f9eb1cd7ce7e7334d8d549f74f72 - Syncs dep updates from the dotnet repo
> Fix JS example with credentials, sync JS and dotnet dependency updates

- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/python/template/client/test_client.mustache
- config/clients/python/template/client/test_client_sync.mustache
For the Go, JS, and Python SDKs make passing no deletes or writes to the `write` command perform a no-op and just return an empty response
Part of #299
SDK PRs to come shortly
> chore: add test to cover not sending empty array when other has data

- config/clients/dotnet/template/Client_OAuth2Client.mustache
- config/clients/dotnet/template/Client_Utils.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/js/template/credentials/credentials.ts.mustache
- config/clients/js/template/tests/helpers/nocks.ts.mustache
- config/clients/python/template/oauth2.mustache
- config/clients/python/template/oauth2_sync.mustache
- config/clients/python/template/oauth2_test.mustache
- config/clients/python/template/oauth2_test_sync.mustache
Updates the remaining SDKs to use the correct content type when making a token request.
* .net - Needed to move to using `FormUrlEncodedContent` as the body and then the runtime will handle setting the `Content-Type` for us
* Go - no work needed as this is done by the `oauth2` package we included
* JS - Set the header on the request and axios will serialize for us
* Python - Set the header and pass `post_params` instead of body
This has been verified by running all 4 examples and providing credentials, where possible tests have been amended to assert we're passing the right header/body.
Closes #284
Language PRs to follow
> fix: use correct content type for token request

- config/clients/go/template/example/README.md
- config/clients/go/template/example/example1/go.mod.mustache
- config/clients/go/template/go.mod.mustache
Bumps the go requirement to v1.21 in line with the support policy of the last 2 major version (1.21 and 1.22).
https://github.com/openfga/go-sdk/pull/77
> chore(go-sdk): bump to go 1.21

- config/clients/dotnet/template/README_initializing.mustache
- config/clients/go/template/README_initializing.mustache
- config/clients/java/template/README_initializing.mustache
- config/clients/js/template/README_initializing.mustache
- config/clients/python/template/README_initializing.mustache
> chore(docs): add note about initializing the `OpenFgaClient` only once

- config/clients/java/template/client-ClientWriteResponse.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
For the Java SDK make passing empty deletes and empty writes to the write command perform a server call without content
Part of https://github.com/openfga/sdk-generator/issues/299 and https://github.com/openfga/sdk-generator/issues/306
SDK PRs to come shortly
> java-sdk calling the server without content when submitting empty deletes and writes

- config/clients/java/template/.github/workflows/main.yml.mustache
Port back of https://github.com/openfga/java-sdk/pull/55
Updates `gradle-build-action` to version `3.0.0`
> chore(java-sdk): bump gradle-build-action dependency

- config/clients/java/template/libraries/native/ApiClient.mustache
Fixes https://github.com/openfga/java-sdk/issues/65. The intention is to avoid unnecessary clones of the object mapper for less overhead. Tests are expected to pass, given that this is an internal change with untouched contracts.
> fix(java-sdk): fix clone of object mapper

- Makefile
- config/clients/python/template/api.mustache
- config/clients/python/template/api_client.mustache
- config/clients/python/template/api_client_sync.mustache
- config/clients/python/template/api_test.mustache
- config/clients/python/template/api_test_sync.mustache
- config/clients/python/template/credentials_test.mustache
- config/clients/python/template/oauth2.mustache
- config/clients/python/template/oauth2_sync.mustache
- config/clients/python/template/oauth2_test.mustache
- config/clients/python/template/oauth2_test_sync.mustache
- config/clients/python/template/test-requirements.mustache
This PR rolls up the changes in the following PRs from the Python SDK and updates the generator to incorporate those updates:
- https://github.com/openfga/python-sdk/pull/78
- https://github.com/openfga/python-sdk/pull/79
To summarize, these changes introduce auto-retry support for failed requests (429, 500, 502, ...) to the `/oauth/token` auth endpoint, and enhance existing auto-retry of failed requests to the OpenFGA server to cover 5xx series error responses. In both cases, 501 is excluded from retries.
This PR also updates the makefile to generate a more robust code coverage report when running unit tests of the Python SDK. There is 100% coverage of these changes.
> feat(python): support auto-retry of failed network requests

- config/clients/java/template/client-ClientListObjectsRequest.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
Fixes #331 
Java SDK: Add support for global Context for the ListObjects API. The new field is optional and the change is backward compatible.
> feat(java-sdk): Allow global context for ListObjects

- config/clients/python/.openapi-generator-ignore
- config/clients/python/config.overrides.json
- config/clients/python/template/configuration.mustache
- config/clients/python/template/test_configuration.mustache
This PR:
- Ensures the `RetryParams` class does not permit `max_retry` to exceed the hardcoded limit of 15 retries, as configured by the SDK Generator.
- Includes a new comprehensive unit test file for the SDK's Configuration class, which was not present before. These tests increase our code coverage substantially.
Other small bug fixes and improvements to the Configuration were made, which I noticed as I was writing the unit tests:
- `disabled_client_side_validations` was not working reliably and was unnecessarily using the `__setattr__` magic method. This introduced a tiny and unnecessary performance hit when making ANY configuration adjustments. I've created a getter/setter for this property to resolve this.
- `min_wait_in_ms` was not checking for negative values, or indeed if the …
> fix(python-sdk): honor retryMaxAllowedNumber

- config/clients/dotnet/template/Client_ApiClient.mustache
- config/clients/dotnet/template/Client_OAuth2Client.mustache
- config/clients/dotnet/template/README_retries.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/go/template/README_retries.mustache
- config/clients/java/template/README_initializing.mustache
- config/clients/java/template/README_retries.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
- config/clients/js/template/README_retries.mustache
- config/clients/python/template/README_retries.mustache
- config/common/files/README.mustache
Adds a process for documenting the retry strategy of each SDK in the readme following the other SDK specific readme pieces by introducing a `README_retries.mustache` file that will be rendered into the readme.
* 8db7d1ace191cede02976016c91c0abbe2928644 - Introduces retry handling on the oauth2 client for dotnet, this is exercised by the test added in api client.
* b33b16dbb3f39cd2e57b52c405f84ffd003f56d5 - Introduces retry handling on the oauth2 client for java, this is verified manually as unfortunately the features of the HTTP mocking library there are limited.  It can only register one response per URL and I can’t workaround this using the `doAction` feature (e.g track number of requests and change response depending on request count), because any request after the first fails for …
> docs: include retry information in the readme for SDKs

- config/clients/java/template/client-ClientListRelationsRequest.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
Adds support for passing context and contextual tuples to a `listRelations` call, also adds a test to cover the addition for context on `listObjects`
Closes #334
Generates openfga/java-sdk/pull/72
> feat(java-sdk): support context and contextual tuples on listrelations

- config/clients/js/config.overrides.json
- config/clients/js/template/.github/dependabot.yaml
- config/clients/js/template/.madgerc
- config/clients/js/template/common.mustache
Fixes the circular import being flagged by the new version of madge
> fix(js-sdk): resolve circular import

- config/clients/js/template/README_calling_api.mustache
Corrects the readme docs casing for contextual tuples
https://github.com/openfga/js-sdk/pull/94
Part of https://github.com/openfga/sdk-generator/issues/346
> docs(js): correct casing for contextual tuples

- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/creds-AccessToken.java.mustache
- config/clients/java/template/creds-AccessTokenTest.java.mustache
Ports the following Go and Java changes:
* https://github.com/openfga/java-sdk/pull/77
* https://github.com/openfga/java-sdk/pull/76
* https://github.com/openfga/go-sdk/pull/91
* https://github.com/openfga/go-sdk/pull/78
> Port Go and Java changes

- .github/workflows/main.yaml
- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/.github/workflows/main.yaml.mustache
- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/client-ClientListUsersRequest.java.mustache
- config/clients/java/template/client-ClientListUsersResponse.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/config-ClientListUsersOptions.java.mustache
Adds support for list users API to Java.
I've not introduced to the example project because that needs a docker container to be published with the API because it's ran as part of the integration tests.
Also syncs the latest dependency updates
Part of #329
> feat(java-sdk): support list users

- config/clients/java/template/.github/workflows/main.yaml.mustache
Noticed a warning about this on the release job so figured we should switch over, it's functionally identical just renamed
Also changes the publish step to the new way of setting up gradle and then calling the tasks as `arguments` is now deprecated too
https://github.com/openfga/java-sdk/actions/runs/8925573963
> ci(java-sdk): handle gradle action deprecations

- Makefile
This pins the default ref for the openfga/api repo to be the commit prior to the context in assertions API addition so that we don't generate the interfaces and changes related to this until it is stable
- [] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
> chore: pin to prior commit on api repo for now

- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
Enables overriding the store ID using `client.go` for all APIs except for ListStores and CreateStore.
For endpoints that use the store ID, a `StoreId` was added to its respective request options. If set, it will be used when making the request. If not set, the store ID configured for the client will be used instead.
```go
client, err := NewSdkClient(&ClientConfiguration{
ApiUrl:  os.GetEnv("FGA_API_URL"),     
StoreId: os.GetEnv("FGA_STORE_ID"),
})
if err != nil {
// handle error
}
// Uses StoreId from ClientConfiguration
got, err := client.GetStore(context.Background()).Execute()
if err != nil {
// ....
}
fmt.Printf("Got store %v", got.Name)
// store can be overridden
storeOverrideOptions := ClientGetStoreOptions{
StoreId: "01RXYB9SWCFGFCX1QZA9DN8T4Y",
}
got, err = …
```
> feat(go-sdk): Allow StoreId to be overridden per-request

- config/clients/go/template/client/client.mustache
- config/clients/go/template/configuration.mustache
Fixed set HTTP Client of Go SDK.
Closes https://github.com/openfga/sdk-generator/issues/370
> fix(go-sdk): set http client

- Makefile
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/client-ClientListUsersResponse.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/python/template/README_calling_api.mustache
- config/clients/python/template/api_test.mustache
- config/clients/python/template/api_test_sync.mustache
- config/clients/python/template/client/test_client.mustache
- config/clients/python/template/client/test_client_sync.mustache
Removes excluded_users from the response of all SDKs as it was removed from OpenFGA with https://github.com/openfga/api/pull/171. 
This feature was originally a well-intentioned way to communicate any negations that may exist on public-typed wildcard (e.g. user:*) as a means of being abundantly clear about what a user:* result entails. However, as we discover more possible situations where excluded users could arise, we realize that we were making a premature decision about the API. We fully intend to re-add excluded_users at some point in the future but may or may not be a flattened list as previously implemented.
**Please note:** 
- This is technically a breaking but is acceptable provided that the ListUsers API is still experimental
- The API commit this PR is based off of is not …
> Removing excluded users from ListUsers response

- config/clients/js/patches/add-method-specific-attributes.patch
When generating the patch I overlooked including the `fga-client.request.model_id` attribute, this corrects that mistake and includes the model id when it is included in the request.
> fix(js-sdk): add missing request model id attribute

- config/clients/python/template/.github/workflows/main.yaml.mustache
This PR updates the template for the Python SDK's GitHub workflow, bumping the `setup-python` action from `5.1.0` to `5.1.1`.
https://github.com/openfga/python-sdk/pull/111
> chore(python-sdk:ci): bump `setup-python` action

- config/clients/js/config.overrides.json
- config/clients/js/template/.github/workflows/main.yaml.mustache
- config/clients/js/template/docs/opentelemetry.md.mustache
- config/clients/js/template/example/README.md.mustache
- config/clients/js/template/example/opentelemetry/.env.example
- config/clients/js/template/example/opentelemetry/.npmrc
- config/clients/js/template/example/opentelemetry/README.md
- config/clients/js/template/example/opentelemetry/instrumentation.mjs
- config/clients/js/template/example/opentelemetry/opentelemetry.mjs
- config/clients/js/template/example/opentelemetry/package.json.mustache
- config/clients/python/config.overrides.json
- config/clients/python/template/docs/opentelemetry.md.mustache
Adds an example app that covers how to configure OpenTelemetry, this is mostly based on the Python example (the readme is basically the same also) with one change in that this runs in a loop because I just couldn't get the JS exporter to flush the metrics when the script exits
https://github.com/openfga/js-sdk/pull/130
> chore(js-sdk): add opentelemetry example app

- config/clients/python/template/src/api_client.py.mustache
- config/clients/python/template/src/sync/api_client.py.mustache
Updates the Python SDK Code to not set fga-client.request.client_id attribute if the client_id is None
Fixes: https://github.com/openfga/python-sdk/issues/117
> fix(python-sdk): Do not set fga-client.request.client_id if client_id  is None

- config/clients/js/template/package.mustache
This PR bumps the `axios` dependency used by the JS SDK to address https://github.com/axios/axios/issues/6463
Generates the same output as https://github.com/openfga/js-sdk/pull/137
> chore(js-sdk): bump `axios` dependency to `^1.7.4`

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/.github/workflows/fossa.yaml
- config/clients/java/template/.github/workflows/main.yaml.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/example/example1/build.gradle.mustache
- feat: support [OpenTelemetry metrics reporting](https://github.com/openfga/java-sdk/blob/main/docs/OpenTelemetry.md) [\#94](https://github.com/openfga/java-sdk/pull/94) [\#95](https://github.com/openfga/java-sdk/pull/95)
- chore: update dependencies [\#100](https://github.com/openfga/java-sdk/pull/100) [\#101](https://github.com/openfga/java-sdk/pull/100) [\#102](https://github.com/openfga/java-sdk/pull/102) [\#103](https://github.com/openfga/java-sdk/pull/103)
---
Generated https://github.com/openfga/java-sdk/pull/104
> release(java-sdk): v0.6.0

- config/clients/java/template/telemetry-Metrics.java.mustache
This PR follows up on #407 to ensure the SDK output includes the proper SDK version for the OpenTelemetry MeterProvider signature.
> fix(java-sdk): ensure `MeterProvider` uses the correct package version

- config/clients/java/config.overrides.json
- config/clients/js/config.overrides.json
- config/clients/python/config.overrides.json
- config/common/files/README.mustache
This pull request replaces the `supportsOpenTelemetry` configuration override with a `openTelemetryDocumentation` variable. This enables us to change the link/path used in the README to the OpenTelemetry documentation in a manner appropriate to the standards of the target programming language (for example, pascal for Java, snake for Python, etc.)
As an example, in Java's case, it is preferable to output the OpenTelemetry documentation to https://github.com/openfga/java-sdk/blob/main/docs/OpenTelemetry.md instead of https://github.com/openfga/java-sdk/blob/main/docs/opentelemetry.md, as the casing for all the other generated documentation uses pascal case.
This change updates the base README template to point to the configured filename, rather than the generic `opentelemetry.md` filename.
> docs: allow configuration of generated OpenTelemetry documentation path

- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/java/template/README_calling_api.mustache
- config/clients/python/template/README_calling_api.mustache
Some of the _Stores_ links are broken, e.g.:
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/README.md?plain=1#L250
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/README.md?plain=1#L268
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/README.md?plain=1#L291
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/README.md?plain=1#L308
Similarly in [go-sdk](https://github.com/openfga/go-sdk), [python-sdk](https://github.com/openfga/python-sdk), and [dotned-sdk](https://github.com/openfga/dotnet-sdk).
> fix: update `Stores` links

- config/clients/python/template/.github/ISSUE_TEMPLATE/bug_report.md.mustache
- config/common/files/CONTRIBUTING.md.mustache
The links to `SECURITY.md` in:
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/CONTRIBUTING.md?plain=1#L46,
- https://github.com/openfga/java-sdk/blob/4947d98a11711eddfbde88caacf36af77da5dcbd/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L10,
are broken.
Similarly in [go-sdk](https://github.com/openfga/go-sdk), [python-sdk](https://github.com/openfga/python-sdk), and [dotned-sdk](https://github.com/openfga/dotnet-sdk).
I decided to link directly to [`SECURITY.md`](https://github.com/openfga/.github/blob/main/SECURITY.md).
> fix: update links to `SECURITY.md`

- config/clients/js/template/.github/workflows/main.yaml.mustache
- config/clients/js/template/README_initializing.mustache
- config/clients/js/template/README_retries.mustache
- config/clients/js/template/client.mustache
- config/clients/js/template/configuration.mustache
- config/clients/js/template/docs/opentelemetry.md.mustache
- config/clients/js/template/example/README.md.mustache
- config/common/files/.github/workflows/semgrep.yaml
Ports some PRs across from the JS SDK
https://github.com/openfga/js-sdk/pull/161
https://github.com/openfga/js-sdk/pull/164
> chore(js-sdk): port back sdk changes

- config/clients/python/template/src/credentials.py.mustache
- config/clients/python/template/test/credentials_test.py.mustache
This pull request introduces the `_parse_issuer` function, enhancing the validation and normalization of issuer URLs for OAuth token requests. It ensures URLs adhere to standards by verifying schemes and appending a default path if needed. 
This pull request introduces a new function, `_parse_issuer`, to the authentication system, specifically designed to enhance the validation and normalization of issuer URLs used in OAuth token requests. 
This function systematically checks and corrects the structure of the issuer URL, ensuring it adheres to expected standards, such as including a valid scheme (http or https) and appending a default endpoint path if none is provided. 
Additionally, comprehensive tests have been added to validate the functionality of this new method against various edge …
> feat(token): token endpoint is now configurable

- config/clients/go/template/telemetry/telemetry.mustache
- config/clients/go/template/telemetry/telemetry_test.mustache
Fix the data race around the `telemetry.TelemetryInstances` variable.
`TelemetryInstances` should not be exported, but it cannot be renamed for backwards compatibility.
Before fix:
```shell
go test -race -run ^TestGetRace$ github.com/openfga/go-sdk/telemetry
```
Output:
```
==================
WARNING: DATA RACE
Read at 0x00000094a240 by goroutine 9:
github.com/openfga/go-sdk/telemetry.Get()
/go-sdk/telemetry/telemetry.go:75 +0x47
github.com/openfga/go-sdk/telemetry.TestGetRace.func1()
/go-sdk/telemetry/telemetry_test.go:244 +0x73
Previous write at 0x00000094a240 by goroutine 11:
github.com/openfga/go-sdk/telemetry.Get()
/go-sdk/telemetry/telemetry.go:76 +0x67
github.com/openfga/go-sdk/telemetry.TestGetRace.func1()
/go-sdk/telemetry/telemetry_test.go:244 +0x73
```
- Example in the …
> fix(go-sdk): data race of the TelemetryInstances variable

- config/clients/python/template/src/client/client.py.mustache
- config/clients/python/template/src/sync/client/client.py.mustache
Currently the Python SDK is sending the sdk method header for all requests, the expectation (and behaviour in other SDKs) for this header is that it is only sent for SDK methods that are wrappers of APIs as the intent is to provide a way for implementors of OpenFGA to track usage of these SDK wrapper methods.
So it should be sent for:
- `read_latest_authorization_model`
- `write`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode
- `write_tuples`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode (handled via `write`)
- `delete_tuples`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode (handled via `write`)
- `batch_check`
-   - Should also send `CLIENT_BULK_REQUEST_ID_HEADER`
- `list_relations`
- …
> fix(python): correct usage of the sdk method header

- Makefile
- config/clients/python/template/test/client/client_test.py.mustache
- config/clients/python/template/test/credentials_test.py.mustache
- config/clients/python/template/test/sync/client/client_test.py.mustache
`make test-client-python` doesn't error if the tests error, which isn't really ideal. So, make it error.
~Unfortunately this PR will fail python CI~
> build(python): fix test command not exiting with an error

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/dotnet/template/example/Example1/Example1.cs
- config/clients/dotnet/template/models_test.mustache
- config/clients/go/CHANGELOG.md.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/example/example1/example1.go
- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/example/example1/src/main/java/dev/openfga/sdk/example/Example1.java
- config/clients/java/template/example/example1/src/main/kotlin/dev/openfga/sdk/example/KotlinExample1.kt
- config/clients/js/CHANGELOG.md.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/js/template/example/example1/example1.mjs
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/js/template/tests/helpers/nocks.ts.mustache
- config/clients/js/template/tests/index.test.ts.mustache
- config/clients/python/CHANGELOG.md.mustache
- config/clients/python/template/README_calling_api.mustache
- config/clients/python/template/example/example1/example1.py.mustache
- config/clients/python/template/test/api_test.py.mustache
- config/clients/python/template/test/client/client_test.py.mustache
- config/clients/python/template/test/sync/api_test.py.mustache
- config/clients/python/template/test/sync/client/client_test.py.mustache
Updating readable names to use uuids
document:name becomes document:0192ab2d-d36e-7cb3-a4a8-5d1d67a300c5
https://github.com/openfga/sdk-generator/issues/276#issuecomment-2421958125
> docs:replace readable names with uuid

- config/clients/python/template/example/example1/example1.py.mustache
- config/clients/python/template/src/client/client.py.mustache
- config/clients/python/template/src/sync/client/client.py.mustache
- config/clients/python/template/test/client/client_test.py.mustache
- config/clients/python/template/test/sync/client/client_test.py.mustache
This PR fixes some minor issues I noticed while updating the `openfga/api` sha on `main. Splitting out to a separate PR to help review.
They are as follows:
- the `ListUsers` API differs on the shape of `contextual_tuples`, rather than an object with a `tuple_keys` property it just takes the array directly. So we don't need the `ContextualTupleKeys` type
- `read_latest_authorization_model` errors if there are no models
- `list_users` in the example was using the wrong types
https://github.com/openfga/python-sdk/pull/147
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :) 
It differs from other endpoints in that it isn't an object but just an array directly
> Minor Python fixes

- config/clients/python/template/src/configuration.py.mustache
- config/clients/python/template/src/telemetry/attributes.py.mustache
- config/clients/python/template/src/telemetry/configuration.py.mustache
- config/clients/python/template/src/telemetry/counters.py.mustache
- config/clients/python/template/src/telemetry/histograms.py.mustache
- config/clients/python/template/src/telemetry/metrics.py.mustache
This PR removes the `Optional` type hinter, as guidance for Python 3.10+ and [PEP 604's introduction](https://peps.python.org/pep-0604/) is to phase it out in favor of a simple `None` union type. Note that these are functionally identical and do not affect the method signature for existing integrations.
- https://github.com/openfga/python-sdk/pull/148
> chore(python-sdk): remove Optional typings

- Makefile
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/client-OpenFgaClientIntegrationTest.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/python/template/test/api_test.py.mustache
- config/clients/python/template/test/sync/api_test.py.mustache
This is based on #446 as it handles some changes to help with the validation, once that is merged I will update to remove those commits.
This updates to the latest version of openfga/api that is included in OpenFGA v1.7.0, with the
following interesting changes included. These are mostly changes to the underlying models and will not require
any changes to the individual codebases aside from potential test changes.
- Adds support for contextual tuples on the assertions API, needs OpenFGAClient updating to support this which is tracked in #449
- Changes min/max page size for read api, should not impact any SDK other than Python
- Adds a new response type for 403 responses and changes the existing cancelled response
- Changes min/max for contextual_tuples, should not impact any SDK other …
> Update API ref

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/go/CHANGELOG.md.mustache
- config/clients/java/CHANGELOG.md.mustache
- config/clients/js/CHANGELOG.md.mustache
- config/clients/python/CHANGELOG.md.mustache
This introduces an `unreleased` section to the changelog with the intention of tracking changes that are yet to be released in each SDK in an attempt to reduce the effort required to cut a new release.
It also add any unreleased changes to this header, it does not attempt to add any enforcement of this.
> docs: add unreleased section to changelogs

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/Client/Client.mustache
- config/clients/dotnet/template/Client/ClientConfiguration.mustache
- config/clients/dotnet/template/Client_ApiClient.mustache
- config/clients/dotnet/template/Client_BaseClient.mustache
- config/clients/dotnet/template/Client_OAuth2Client.mustache
- config/clients/dotnet/template/Client_RequestBuilder.mustache
- config/clients/dotnet/template/Configuration_Configuration.mustache
- config/clients/dotnet/template/Configuration_Credentials.mustache
- config/clients/dotnet/template/Configuration_TelemetryConfig.mustache
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/OpenTelemetry.md.mustache
- config/clients/dotnet/template/OpenTelemetryDocs_custom.mustache
- config/clients/dotnet/template/README.mustache
- config/clients/dotnet/template/README_retries.mustache
- config/clients/dotnet/template/Telemetry/Attributes.cs.mustache
- config/clients/dotnet/template/Telemetry/Counters.cs.mustache
- config/clients/dotnet/template/Telemetry/Histograms.cs.mustache
- config/clients/dotnet/template/Telemetry/Meters.cs.mustache
- config/clients/dotnet/template/Telemetry/Metrics.cs.mustache
- config/clients/dotnet/template/api.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/dotnet/template/example/Example1/Example1.cs
- config/clients/dotnet/template/example/OpenTelemetryExample/.env.example
- config/clients/dotnet/template/example/OpenTelemetryExample/OpenTelemetryExample.cs
- config/clients/dotnet/template/example/OpenTelemetryExample/OpenTelemetryExample.csproj
- config/clients/dotnet/template/netcore_project.mustache
- config/clients/dotnet/template/netcore_testproject.mustache
Adds initial OpenTelemetry metrics to the .NET SDK
Generates: https://github.com/openfga/dotnet-sdk/pull/69
> feat(dotnet): export opentelemetry metrics

- config/common/config.base.json
I have reduced the default retry behavior from 15 retries to 3 as requested in issue #417 
closes #417
> fix : change default retry policy

- config/clients/go/template/client/client.mustache
Backports the change to add getter/setter methods to the `SdkClient` interface
https://github.com/openfga/go-sdk/pull/155
> fix(go-sdk): update client interface with store and model getter/setter

- config/clients/js/CHANGELOG.md.mustache
- config/clients/js/template/client.mustache
- config/clients/js/template/example/example1/example1.mjs
- config/clients/js/template/example/opentelemetry/opentelemetry.mjs
- config/clients/js/template/package.mustache
- config/clients/js/template/telemetry/attributes.ts.mustache
- config/clients/js/template/telemetry/configuration.ts.mustache
- config/clients/js/template/tests/client.test.ts.mustache
- config/clients/js/template/tests/helpers/nocks.ts.mustache
- config/clients/js/template/tests/telemetry/attributes.test.ts.mustache
> [!WARNING]  
> Breaking Change! This change renames the existing `batchCheck` method (which calls the `/check` API in parallel) to `clientBatchCheck`. If you would like to continue to use the client-side batch check, replace your calls to `batchCheck` with `clientBatchCheck`.
Introduces support for the server-side batch check API, released in [OpenFGA v1.8.2](https://github.com/openfga/openfga/releases/tag/v1.8.2).
https://github.com/openfga/js-sdk/pull/185
> feat(js-sdk)!: Support Server Batch Check

- config/clients/js/CHANGELOG.md.mustache
- config/clients/js/template/baseApi.mustache
- config/clients/js/template/credentials/credentials.ts.mustache
Ports fix for using axios instance in credentials requests
https://github.com/openfga/js-sdk/pull/193
> fix: use provided axios instance in credentials refresh

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/example/example1/build.gradle.mustache
I started working on openfga/java-sdk#127, but I realized that the `java-sdk` repo contains manually changed files not generated through the `sdk-generator`. This leads me to first align the code between the `sdk-generator` and the `java-sdk`.
> [!TIP]
> I also believe that to prevent such modifications, all `*-sdk` repos should be set to read-only mode. As outlined in the contribution guides, all changes should be made thought the `sdk-generator`. As a very fist step, a GitHub Workflow could be introduced to manually generate SDKs.
> feat(java-sdk): Adjust sdk-generator to be compatible with java-sdk

- config/clients/python/template/src/client/client.py.mustache
- config/clients/python/template/src/client/models/expand_request.py.mustache
- config/clients/python/template/src/sync/client/client.py.mustache
This PR adds support for `contextual_tuples` in `expand` requests. (It follows up with support for auto-generated changes already included in a previous commit, #469.)
- https://github.com/openfga/python-sdk/pull/164
- https://github.com/openfga/js-sdk/pull/196/commits/bfd46795c9077a64b1b3684278cf4ed33388c459
> feat(python-sdk): support `contextual_tuples` in `expand` requests

- config/clients/go/CHANGELOG.md.mustache
- config/clients/go/config.overrides.json
- config/clients/go/template/api_client.mustache
- config/clients/go/template/api_client_test.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
Syncs a couple PRs over from go-sdk
https://github.com/openfga/go-sdk/pull/162
https://github.com/openfga/go-sdk/pull/160
> chore(go-sdk): sync changes

- config/clients/go/template/client/client.mustache
Backport of the fix in go-sdk to resolve https://github.com/openfga/sdk-generator/issues/483
https://github.com/openfga/go-sdk/pull/166
> fix(go-sdk): backport start time variable read fix from go-sdk

- config/clients/go/template/README_calling_api.mustache
Resolves README issue for ReadChanges where StartTime was included in Options rather than Body
Addresses documentation portion of: https://github.com/openfga/sdk-generator/issues/483
> docs: update readChanges startTime docs to reflect inclusion in body

- config/clients/python/template/src/rest.py.mustache
- config/clients/python/template/src/sync/rest.py.mustache
- config/clients/python/template/test/rest_test.py.mustache
- config/clients/python/template/test/sync/rest_test.py.mustache
This is a minor bug fix to the new `stream` method added to the Python SDK's REST client in 0.9.1: the pool shouldn't close after the request concludes, as the same pool can continue to be used for future requests.
Generates https://github.com/openfga/python-sdk/pull/172
> fix(python-sdk): REST client should not close after `stream` request

- config/clients/python/template/requirements.mustache
- config/clients/python/template/src/sync/rest.py.mustache
- Bumped dependency requirements for urllib3 to specify >= v1.26.19 or >= v2.2.2
- Modified type hints in RESTResponse class to use urllib3.HTTPResponse instead of urllib3.BaseHTTPResponse
> fix(python-sdk): urllib3 compatibility < v2

- config/clients/dotnet/template/netcore_project.mustache
As the SDK is not using features from OpenTelemetry Api the dependency is not needed. The instrumentation of the SDK is done via dotnet mechanism (System.Diagnostic). The appliction which use the SDK should manage and configure the OpenTelemetry packages
Backport of https://github.com/openfga/dotnet-sdk/pull/100 by @m4tchl0ck
> chore(dotnet-sdk): remove dependecy on OpenTelemetry.Api

- config/clients/python/template/src/oauth2.py.mustache
- config/clients/python/template/test/oauth2_test.py.mustache
Use dynamic token issuer URL not applying a scheme and path if they are already provided.
#238 describes the desire to be able to use dynamic token issuer URLs. In my use case, the `/oauth/token` suffix prevents my from using the SDK with Keycloak. This dynamic implementation allows to overcome the issue.
> feat(python): dynamic token issuer

- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/go.mod.mustache
- Resolves issue where if number of checks exceeds MaxParallelRequests * MaxBatchSize a stall occurs.  Ensures that all checks are processed
- Added additional test coverage related to this issue to prevent recurrence of similar issues.
- remove private method from interface to allow mocking
- https://github.com/openfga/go-sdk/issues/191
- https://github.com/openfga/go-sdk/issues/192
> fix(go-sdk): resolve server-side BatchCheck stalling

- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/example/example1/example1.go
- Fix typo on function name in README for Batch Check
- Add BatchCheck example to examples/example1.go
https://github.com/openfga/go-sdk/issues/190
> docs(go-sdk): Add BatchCheck example - fix typo in readme

- config/clients/python/template/requirements.mustache
> fix(python-sdk): remove urllib3 >= 2.2.2 restriction

- config/clients/java/template/libraries/native/ApiClient.mustache
Removes unused imports. #541 removed an unused method, but the change results in a [failing java-sdk build](https://github.com/openfga/java-sdk/actions/runs/14782621289/job/41730928794?pr=164).
Note: we should run lint checks for java on PRs to the generator repo, to catch these issues sooner. Created #542 for this.
https://github.com/openfga/sdk-generator/pull/541
> chore(java-sdk): Remove unused imports

- .github/workflows/main.yaml
Potential fix for [https://github.com/openfga/sdk-generator/security/code-scanning/3](https://github.com/openfga/sdk-generator/security/code-scanning/3)
To fix the problem, add a `permissions` block at the top level of the workflow (just after the `name:` and before `on:`), which will apply to all jobs unless overridden. The minimal required permission for these jobs is `contents: read`, as they only need to check out code and run tests. No job in the provided snippet appears to require write access to the repository or other resources. The change should be made by inserting the following block:
```yaml
permissions:
contents: read
```
immediately after the `name: Run Tests` line (line 1), before the `on:` block.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …
> Potential fix for code scanning alert no. 3: Workflow does not contain permissions

- .github/workflows/semgrep.yaml
Potential fix for [https://github.com/openfga/sdk-generator/security/code-scanning/2](https://github.com/openfga/sdk-generator/security/code-scanning/2)
To fix the problem, add a `permissions` block to the workflow or the specific job to restrict the `GITHUB_TOKEN` to the least privilege required. In this case, since the job only checks out code and runs Semgrep, it only needs read access to repository contents. The best way to fix this is to add `permissions: contents: read` at the job level (under `semgrep:`), which will ensure that the token cannot be used for any write operations. This change should be made directly under the job definition (after `name: Scan` and before `runs-on:`).
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 2: Workflow does not contain permissions

- .github/workflows/main.yaml
Potential fix for [https://github.com/openfga/sdk-generator/security/code-scanning/7](https://github.com/openfga/sdk-generator/security/code-scanning/7)
To fix the problem, add a `permissions` block to the workflow file. The best way to do this is to add the block at the top level of the workflow (just below the `name:` and before `on:`), so that all jobs inherit the minimal permissions unless they explicitly override them. The minimal required permission for most CI jobs is `contents: read`, which allows the workflow to check out code but not to write to the repository. This change does not affect existing functionality, as none of the jobs shown require write access.
**What to change:**  
- Edit `.github/workflows/main.yaml`.
- Insert the following block after the `name:` line and …
> Potential fix for code scanning alert no. 7: Workflow does not contain permissions
