openfga/sdk-generator

- config/clients/go/template/.github/workflows/main.yaml
> chore(go-sdk): bump go version used for ci

- config/common/files/README.mustache
Correct output for about OpenFGA
> fix: proper anchor for about

- README.md
Add in contributing guideline for SDKs.
> feat: add in contributing guideline for SDKs

- docker/sandcastle.builder.Dockerfile
This deletes an old docker file that is no longer used in the project
> chore: delete unusued docker file

- README.md
- config/common/files/README_project_introduction.mustache
> chore(all-sdks): update project introduction in README

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/Client_ApiClient.mustache
> chore(dotnet-sdk): add changelog for v0.0.3

- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/fga_test.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/js/template/tests/index.test.ts.mustache
Use a uuid for the identifier and a type for the user
We want to encourage people to use a type for the users, in order to benefit from optimizations we will be making, considering that people look at examples and tests for ideas, it would be better if they pointed to the correct representation we want to encourage.
> chore(all-sdks): update user in examples & tests

- config/clients/python/template/api_client.mustache
Since file is not used as part of the API, we will remove reference to file
N/A
> fix: remove file reference for python

- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
> chore(js-sdk): bump deps

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/netcore_testproject.mustache
> release(dotnet-sdk): v0.1.0

- Makefile
- config/clients/python/template/.github/workflows/main.yaml
> feat(python-sdk): publish to pypi

- config/clients/js/patches/add-missing-first-param.patch
line number got shifted - thus, we need to update patch file
> chore: update JS patch file

- config/clients/python/template/.github/workflows/main.yaml
- config/clients/python/template/setup.mustache
> fix(python-sdk): update classifier and ci file

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/netcore_testproject.mustache
changes:
- feat: regenerate from latest API Document, changes include: - documentation fixes - types that represent enabling wildcards in authorization models
- fix: send authorization header to server when ApiToken used
- chore: update test dependencies
> release(dotnet): v0.1.2

- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/python/template/README_calling_api.mustache
Clean up the READMEs for various SDKs so that reader are able to run by just copy and paste.
Close https://github.com/openfga/sdk-generator/issues/66
> fix: update README examples for all SDK

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/template/api_test.mustache
- config/clients/dotnet/template/netcore_testproject.mustache
- config/clients/go/CHANGELOG.md.mustache
- config/clients/go/template/fga_test.mustache
- config/clients/go/template/go.mod.mustache
- config/clients/go/template/go.sum
- config/clients/js/CHANGELOG.md.mustache
- config/clients/js/patches/add-missing-first-param.patch
- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
- config/clients/js/template/tests/index.test.ts.mustache
- config/clients/python/CHANGELOG.md.mustache
- config/clients/python/template/api_test.mustache
- Support for OpenFGA v0.3.0
- Update ListObjects support [BREAKING]
- Update models
- Upgrade dependencies
Note: In the JS SDK, we cannot upgrade to `package-lock.json` to `version: 3` as that causes snyk to break
> feat: update to support OpenFGA 0.3.0

- config/clients/dotnet/template/README_calling_api.mustache
- config/clients/go/template/README_calling_api.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/python/template/README_calling_api.mustache
> chore(all-sdks): update the readmes with ListObjects and Read changes

- README.md
- config/clients/js/template/.github/workflows/main.yaml
> chore: update readme and js ci env

- config/clients/go/template/go.mod.mustache
- config/clients/go/template/go.sum
- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
> chore: upgrade deps

- config/clients/go/template/go.mod.mustache
- config/clients/go/template/go.sum
- config/clients/go/template/oauth2/internal/token.go
source: https://github.com/golang/oauth2/commit/e07593a4c41a489556d019d1ad4d82e9ee66b4a7
> chore(deps): drop `golang.org/x/net` dependency

- .github/workflows/tests.yml
- config/clients/dotnet/template/.github/workflows/main.yaml.mustache
- config/clients/go/template/.github/workflows/main.yaml
- config/clients/js/template/.github/workflows/main.yaml
- config/clients/python/template/.github/workflows/main.yaml
Integrations work better with external contributors
> chore(ci): remove snyk & fossa ci actions, we will rely on the integrations

- Makefile
> chore(build): bump openapi generator to `v6.4.0`

- config/clients/go/template/.github/workflows/main.yaml
- config/clients/go/template/README_initializing.mustache
- require go >=1.20.3 for the CI
- fix documentation for initializing the SDK (contributed by @DGuhr)
- add documentation on client credentials config
- https://github.com/openfga/go-sdk/pull/8
- https://github.com/openfga/go-sdk/commit/3ffb132343f1c7220038f7e26ed16aed17222315
> fix(go-sdk): documentation fixes

- config/clients/python/config.overrides.json
- config/clients/python/template/api_test.mustache
- https://github.com/openfga/python-sdk/issues/11
> fix(python-sdk): missing sdk id

- config/clients/js/template/.github/workflows/main.yaml
- config/clients/js/template/package.mustache
- Generates: https://github.com/openfga/js-sdk/pull/13
> chore(js-sdk): fix permissions for ci

- .github/workflows/main.yaml
- config/clients/dotnet/template/.github/workflows/main.yaml.mustache
- config/clients/go/template/.github/workflows/main.yaml
- config/clients/js/template/.github/workflows/main.yaml
- config/clients/python/template/.github/workflows/main.yaml
> chore(ci): run main workflow on merge queues in generator and all SDKs

- config/clients/go/config.overrides.json
- config/clients/go/template/.github/workflows/main.yaml
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/client/errors.mustache
- Includes:
- https://github.com/openfga/go-sdk/pull/25
- https://github.com/openfga/go-sdk/pull/24
- https://github.com/openfga/go-sdk/pull/17
> fix(go-sdk): fix null ptr exceptions and issues with Read

- Makefile
> chore(go): run go fmt

- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
Add auth model validation/connection check on batch check/list relations/non transaction write.  This allows proper error to return  
Related to  https://github.com/openfga/go-sdk/issues/21
> fix(go-sdk): validation connection and model for batch operations

- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
Generates: https://github.com/openfga/js-sdk/pull/21
Resolves: Regular Expression Denial of Service in semver (non-prod dep), ref:
- https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
- https://nvd.nist.gov/vuln/detail/CVE-2022-25883
- https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795
> chore(js-sdk): upgrade deps & override semver

- README.md
- scripts/setup_new_sdk.sh
> chore: update generator readme

- README.md
- config/common/files/README.mustache
The previous link only works for folks who are already part of the server. This link should work for anyone, and put them in the `#fga-general` channel.
Discord discussion: https://discord.com/channels/759188666072825867/930524706854031421/1133095840676859934
> docs: Use invite link for Discord Server in README

- config/clients/js/template/credentials/credentials.ts.mustache
Original contribution by @KlausVii
SDK PR: https://github.com/openfga/js-sdk/pull/27
> fix(js-sdk): fix token expiry calculation

- config/clients/js/template/.eslintrc.js
- config/clients/js/template/package-lock.mustache
- config/clients/js/template/package.mustache
SDK PR: https://github.com/openfga/js-sdk/pull/28
> chore(js-sdk): update dependencies

- config/clients/java/config.overrides.json
- config/clients/java/template/FgaInvalidParameterException.java.mustache
- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/config-BaseConfiguration.java.mustache
- config/clients/java/template/config-Configuration.java.mustache
- config/clients/java/template/config-ConfigurationTest.java.mustache
- config/clients/java/template/creds-ClientCredentials.java.mustache
- config/clients/java/template/creds-ClientCredentialsTest.java.mustache
Update Java package path so everything is under `dev.openfga.sdk` -- this prevents future conflicts for other Java projects.
> refactor(java): Update Java package path

- config/clients/js/patches/add-missing-first-param.patch
- config/clients/js/template/api.mustache
- config/clients/js/template/apiInner.mustache
- config/clients/js/template/baseApi.mustache
- config/clients/js/template/client.mustache
- config/clients/js/template/common.mustache
- config/clients/js/template/configuration.mustache
- config/common/config.base.json
- Generated PR: https://github.com/openfga/js-sdk/pull/30
> fix(js-sdk): set keep-alive to true

- config/clients/java/.openapi-generator-ignore
- config/clients/java/config.overrides.json
Makes sure only Gradle CI gets rendered
> ci(java): Make sure only Gradle CI is rendered

- config/clients/java/template/OpenFgaApiIntegrationTest.java.mustache
> fix(java): Add .get() on void async requests in test

- config/clients/java/template/README_calling_api.mustache
- config/clients/java/template/README_initializing.mustache
> chore(java): add readme shell

- config/clients/java/template/.github/workflows/main.yml.mustache
- config/clients/java/template/publish.gradle.mustache
Generates https://github.com/openfga/java-sdk/pull/14
> chore(java-sdk): Add GPG signing keys to publish CI workflow

- config/clients/java/CHANGELOG.md.mustache
Generates https://github.com/openfga/java-sdk/pull/15
> chore(java-sdk): Add initial changelog

- config/clients/java/template/.github/workflows/main.yml.mustache
> chore(java-sdk): Update CI triggers

- config/clients/java/config.overrides.json
The Auth0 folks prefer the shorter 'dev.openfga' group id
Generates https://github.com/openfga/java-sdk/pull/18
> chore(java-sdk): Update Maven group ID to 'dev.openfga'

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
Generates https://github.com/openfga/java-sdk/pull/19
> release(java-sdk): v0.0.2 changing the groupId to dev.openfga

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/publish.gradle.mustache
- Generates: https://github.com/openfga/java-sdk/pull/21
> fix(java-sdk): fix publishing to maven central

- config/clients/java/config.overrides.json
- config/clients/java/template/OpenFgaApiTest.java.mustache
- config/clients/java/template/client-HttpRequestAttempt.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
- config/clients/java/template/config-BaseConfiguration.java.mustache
- config/clients/java/template/config-ClientConfiguration.java.mustache
- config/clients/java/template/config-Configuration.java.mustache
- config/clients/java/template/config-ConfigurationOverride.java.mustache
- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
- config/clients/java/template/errors-FgaApiAuthenticationError.java.mustache
- config/clients/java/template/errors-FgaApiInternalError.java.mustache
- config/clients/java/template/errors-FgaApiNotFoundError.java.mustache
- config/clients/java/template/errors-FgaApiRateLimitExceededError.java.mustache
- config/clients/java/template/errors-FgaApiValidationError.java.mustache
- config/clients/java/template/errors-FgaInvalidParameterException.java.mustache
- config/clients/java/template/libraries/native/ApiClient.mustache
- config/clients/java/template/libraries/native/api.mustache
Introduces error modeling and retries
Generates https://github.com/openfga/java-sdk/pull/25
> feat(java-sdk): Introduce error modeling and retries

- config/clients/js/patches/add-missing-first-param.patch
> chore(js): update patch for client js

- config/clients/go/template/.github/dependabot.yml
> chore(go): add dependabot config

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/.github/workflows/main.yml.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/publish.gradle.mustache
chore(java-sdk): automate releases
chore(java-sdk): bump version to 0.2.1
Generates https://github.com/openfga/java-sdk/pull/27
> chore(java-sdk): automate releases

- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
Regenerate and updates to support latest changes in https://github.com/openfga/api/pull/98
https://github.com/openfga/sdk-generator/pull/216
https://github.com/openfga/api/pull/116
https://github.com/openfga/api/pull/98
https://github.com/openfga/go-sdk/pull/54
> refactor(go): normalize deletes field on write api

- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
> release(dotnet-sdk): v0.2.5 with fix read all tuples

- README.md
> chore: add java sdk to readme

- Makefile
- config/clients/go/template/.github/workflows/main.yaml
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/go.mod.mustache
- config/clients/go/template/go.sum.mustache
> fix(go-sdk): incorporate latest API changes

- .github/CODEOWNERS
- config/common/files/.github/CODEOWNERS.mustache
> chore: change owner team to dx

- config/clients/java/template/client-ClientCheckRequest.java.mustache
- config/clients/java/template/client-OpenFgaClient.java.mustache
Generates https://github.com/openfga/java-sdk/pull/41
> fix(java-sdk): add context to ClientCheckRequest

- config/clients/python/patches/open_fga_api.py.patch
- config/clients/python/template/.github/workflows/main.yaml
- config/clients/python/template/api.mustache
- config/clients/python/template/api_client.mustache
- config/clients/python/template/api_client_sync.mustache
- config/clients/python/template/test-requirements.mustache
Generates https://github.com/openfga/python-sdk/pull/58
> chore/python sdk/bump deps

- config/common/files/.github/dependabot.yaml
> chore: add base dependabot file

- config/clients/go/CHANGELOG.md.mustache
> chore(go-sdk): fix v0.3.4 changelog

- config/clients/java/template/creds-OAuth2Client.java.mustache
- config/clients/java/template/creds-OAuth2ClientTest.java.mustache
[java-sdk issue 47](https://github.com/openfga/java-sdk/issues/47)
> fix(java-sdk): client_credentials content type

- config/clients/js/template/package-lock.mustache
This PR updates the `js-sdk` dependencies lockfile template to address a number of Snyk warnings.
N/A
> chore(js-sdk): bump dependencies

- .github/dependabot.yml
This PR enables Dependabot version updates for GitHub Actions within the `sdk-generator` repository.
Closes #214
> ci(dependabot): add config for github actions

- docs/GENERATING-A-NEW-SDK.md
> chore(docs): document generating a new SDK

- config/clients/java/template/build.gradle.mustache
from https://github.com/openfga/java-sdk/pull/56
From https://github.com/openfga/java-sdk/pull/56
Updates spotless gradle plugin
> chore(java-sdk) - update spotless gradle plugin

- README.md
- config/common/config.base.json
- config/common/files/README.mustache
> chore: use slack instead of discord

- config/clients/java/template/client-OpenFgaClient.java.mustache
- config/clients/java/template/client-OpenFgaClientTest.java.mustache
⚠️ This is a behavioral breaking change!
Currently the `OpenFgaClient` reverses the behavior of write transactions based on the `disableTransactions` flag. This PR fixes that, only sending batched write requests if `disableTransactions == true`.
This is a functional breaking change, since the value of `disableTransactions` was being used incorrectly, so now `disableTransactions == true` will actually batch requests, and `disableTransactions == false` will send one (transactional) request.
**Current Behavior**
| `disabledTransactions` value | Behavior |
| --- | --- |
| true | One transactional request sent |
| false | Batched requests sent |
**Behavior with this PR**
| `disabledTransactions` value | Behavior |
| --- | --- |
| true | Batched requests sent |
| false | One transactional …
> fix(java-sdk): fix transactions mode being reversed

- .github/CODEOWNERS
- .github/workflows/main.yaml
- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/.github/workflows/main.yml.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/example/README.md
- config/clients/java/template/example/example1/README.md
- config/clients/java/template/example/example1/build.gradle
- config/common/files/.github/CODEOWNERS.mustache
> release(java-sdk): v0.4.0

- .github/workflows/main.yaml
- config/clients/dotnet/template/.github/workflows/main.yaml.mustache
- config/clients/go/template/.github/workflows/main.yaml
- config/clients/java/template/.github/workflows/main.yml.mustache
- config/clients/js/template/.github/workflows/main.yaml
- config/clients/python/template/.github/workflows/main.yaml
This PR updates the GitHub workflows for this repository and the generated workflows for our SDKs to:
- Apply consistent formatting (indentation, double quotes for strings, etc.)
- Update all GitHub Actions to their latest versions, and versions are identified.
- Ensure all GitHub Actions are using commit hashes.
N/A
> chore(ci): update GitHub Workflows and Actions

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/build.gradle.mustache
Syncs dependency update and preps the v0.4.1 release of the Java SDK
> release(java-sdk): v0.4.1

- config/clients/go/CHANGELOG.md.mustache
> chore(go-sdk): update v0.3.6 release notes

- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/client/client.mustache
Copies openfga/go-sdk/pull/93 and openfga/go-sdk/pull/96 across to the go template
> feat(go-sdk): Add MaxParallelRequests option in ListRelations

- config/clients/go/template/.github/workflows/main.yaml.mustache
from https://github.com/openfga/go-sdk/pull/100
Backport https://github.com/openfga/go-sdk/pull/100 to generator.
https://github.com/openfga/go-sdk/pull/100
> chore(go-sdk): backport codecov version bump

- config/clients/go/template/README_calling_api.mustache
Add back `MaxParallelRequests` documentation for List Users
From https://github.com/openfga/go-sdk/commit/e6b8cb2c7674bfff69735a1baf860aea1941b26c
> chore(go-sdk): fix up MaxParallelRequests docs

- config/clients/go/template/oauth2/internal/token.go
- config/clients/go/template/oauth2/internal/token_test.go
We currently retry every request that fails on a credential request, we should only retry on 429 or 5xx errors (this is what Java and Python do).
Generates https://github.com/openfga/go-sdk/pull/102
> fix(go-sdk): only retry on  client credential requests that are 429 or 5xx

- config/clients/go/template/README_retries.mustache
README in go-sdk project display layout is incorrect. screenshot as below
report issue: 
https://github.com/openfga/go-sdk/issues/104
> fix(go-sdk): Incorrect README Display format

- config/clients/python/template/test-requirements.mustache
Backporting https://github.com/openfga/python-sdk/pull/90 into the SDK Generator
> chore(python-sdk): bump dev dependencies

- config/clients/java/config.overrides.json
- config/clients/java/template/.github/workflows/fossa.yaml
This PR adds a CI GitHub workflow for our FOSSA tooling.
https://github.com/openfga/java-sdk/pull/93
> chore(java-sdk): add FOSSA workflow

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/example/example1/build.gradle.mustache
- fix: Maven build issue
---
Generated https://github.com/openfga/java-sdk/pull/105
> release(java-sdk): v0.6.1

- config/clients/python/template/src/api.py.mustache
- config/clients/python/template/src/sync/api.py.mustache
- config/clients/python/template/test/client/client_test.py.mustache
Fix typo: `retry_parms` -> `retry_params`
https://github.com/openfga/python-sdk/pull/144
> fix(python-sdk): Fix retry parameters typo

- config/clients/python/template/.github/workflows/main.yaml.mustache
- config/clients/python/template/test-requirements.mustache
- config/clients/python/template/test/client/client_test.py.mustache
- config/clients/python/template/test/credentials_test.py.mustache
- config/clients/python/template/test/sync/client/client_test.py.mustache
This PR backports some dependency updates already applied to the Python SDK's repository.
> chore(python-sdk): dependency updates

- .github/workflows/main.yaml
- .github/workflows/semgrep.yaml
- config/clients/dotnet/template/.github/workflows/main.yaml.mustache
- config/clients/go/template/.github/workflows/main.yaml.mustache
- config/clients/java/template/.github/workflows/fossa.yaml
- config/clients/java/template/.github/workflows/main.yaml.mustache
- config/clients/js/template/.github/workflows/main.yaml.mustache
- config/clients/python/template/.github/workflows/main.yaml.mustache
- config/common/files/.github/workflows/semgrep.yaml
This PR updates the various GitHub Actions across our Workflows to their latest versions.
> chore: update github action versions

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
- config/clients/java/template/README_installation.mustache
- config/clients/java/template/build.gradle.mustache
- config/clients/java/template/config-TelemetryConfiguration.java.mustache
- config/clients/java/template/docs/OpenTelemetry.md.mustache
- config/clients/java/template/example/example1/build.gradle.mustache
- config/clients/java/template/telemetry-Metrics.java.mustache
This PR updates the Generator to the current state of the Java SDK repository and it's latest v0.7.1 release.
> release(java-sdk): v0.7.1

- config/clients/go/template/client/client.mustache
…[#144](https://github.com/openfga/go-sdk/issues/144)
References: [#145](https://github.com/openfga/go-sdk/pull/145)
Fixes: [#144](https://github.com/openfga/go-sdk/issues/144)
> Makes client.ClientWriteResponse json marshallable go-sdk PR reference (https://github.com/openfga/go-sdk/pull/145)

- config/clients/js/template/README_api_endpoints.mustache
- config/clients/js/template/README_calling_api.mustache
- config/clients/python/template/README_calling_api.mustache
Changes from docs updates found here:
- https://github.com/openfga/js-sdk/pull/197
- https://github.com/openfga/python-sdk/pull/162
> docs: Update python and JS README for batch check

- config/clients/java/CHANGELOG.md.mustache
- config/clients/java/config.overrides.json
Release v0.8.1 of Java SDK
https://github.com/openfga/java-sdk/pull/151
> release(java-sdk): release v0.8.1

- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
https://github.com/openfga/go-sdk/issues/175
Generates: https://github.com/openfga/go-sdk/pull/183
> fix(go-sdk): ensure defaults set if txn options only partially set

- config/clients/go/CHANGELOG.md.mustache
- config/clients/go/config.overrides.json
- config/clients/go/template/api.mustache
- config/clients/go/template/api_client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/credentials.mustache
- config/clients/go/template/errors.mustache
- config/clients/go/template/go.mod.mustache
- config/clients/go/template/internal/utils/retryutils/retryutils.mustache
- config/clients/go/template/internal/utils/retryutils/retryutils_test.mustache
- config/clients/go/template/oauth2/clientcredentials/clientcredentials.mustache
- config/clients/go/template/oauth2/internal/token.go
- config/clients/go/template/oauth2/internal/token_test.go
- config/clients/go/template/oauth2/oauth2.mustache
- config/clients/go/template/oauth2/token.mustache
Reorganizes the retry and error handling code to be a bit cleaner, retries on network errors when doing the client credentials exchange and logs the retries when debug mode is enabled
> chore(go-sdk): cleanup duplicated code, log retries in debug mode

- config/clients/go/template/api.mustache
> chore(go-sdk): fix retry

- config/clients/go/config.overrides.json
- config/clients/go/template/.golangci.yaml
- config/clients/go/template/README_calling_api.mustache
- config/clients/go/template/api.mustache
- config/clients/go/template/api_client.mustache
- config/clients/go/template/api_test.mustache
- config/clients/go/template/client/client.mustache
- config/clients/go/template/client/client_test.mustache
- config/clients/go/template/model_simple.mustache
- config/clients/go/template/oauth2/clientcredentials/clientcredentials_test.mustache
- config/clients/go/template/oauth2/internal/token.go
- config/clients/go/template/oauth2/internal/token_test.go
- config/clients/go/template/oauth2/oauth2_test.mustache
- config/clients/go/template/oauth2/transport.go
- config/clients/go/template/oauth2/transport_test.go
- config/clients/go/template/telemetry/attributes.mustache
- config/clients/go/template/telemetry/configuration.mustache
backport of implementation of server side batch check for go-sdk
https://github.com/openfga/go-sdk/pull/173
> feat(go sdk): server side batch check

- config/clients/java/template/libraries/native/ApiClient.mustache
Removed an unused function: valueToString
> removed unused function valueToString

- .github/workflows/main.yaml
- config/clients/dotnet/CHANGELOG.md.mustache
- config/clients/dotnet/config.overrides.json
- config/clients/dotnet/template/Client/Client.mustache
- config/clients/dotnet/template/Client/Model/ClientBatchCheckResponse.mustache
- config/clients/dotnet/template/Client/Model/ClientBatchCheckResponseTest.mustache
- config/clients/dotnet/template/Client/Model/ClientExpandRequest.mustache
- config/clients/dotnet/template/Client/Model/ClientListStoresRequest.mustache
- config/clients/dotnet/template/OpenFgaClientTests.mustache
- config/clients/dotnet/template/api.mustache
- config/clients/dotnet/template/example/Example1/Example1.cs
- config/clients/dotnet/template/example/Example1/Example1.csproj
- config/clients/dotnet/template/netcore_testproject.mustache
Syncs back changes done to the SDK as well as several fixes
Includes backport of openfga/dotnet-sdk#100
Generates https://github.com/openfga/dotnet-sdk/pull/102 based on the latest API https://github.com/openfga/api/commit/f9709139a3693f6624efda12a001e242c5d506b6 with:
```bash
make test-client-dotnet OPEN_API_REF=
env:
OPEN_API_REF: f9709139a3693f6624efda12a001e242c5d506b6
```
> chore(dotnet-sdk): fixes and sync back sdk changes

- config/clients/java/template/libraries/native/AbstractOpenApiSchema.mustache
Removed not necessary else condition to improve the readability of the file.
> chore(java-sdk): removed else condition because it's not necessary

- config/clients/java/template/src/main/api/client/OpenFgaClient.java.mustache
> feat(java-sdk): make inner client to interact w/ the API public
